//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollectorInterfaceDBEntities : DbContext
    {
        public CollectorInterfaceDBEntities()
            : base("name=CollectorInterfaceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public void FixEfProviderServicesProblem()
        {
            var instance = System.Data.Entity.SqlServer.SqlProviderServices.Instance;
        }

        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<DevicesType> DevicesTypes { get; set; }
        public virtual DbSet<EnphaseDevice> EnphaseDevices { get; set; }
        public virtual DbSet<EnphaseVariable> EnphaseVariables { get; set; }
        public virtual DbSet<FroniusDataManagerDevice> FroniusDataManagerDevices { get; set; }
        public virtual DbSet<FroniusDataManagerVariable> FroniusDataManagerVariables { get; set; }
        public virtual DbSet<FroniusDevice> FroniusDevices { get; set; }
        public virtual DbSet<FroniusVariable> FroniusVariables { get; set; }
        public virtual DbSet<ModbusDevice> ModbusDevices { get; set; }
        public virtual DbSet<ModbusVariable> ModbusVariables { get; set; }
        public virtual DbSet<SmartMeterDevice> SmartMeterDevices { get; set; }
        public virtual DbSet<SmartMeterVariable> SmartMeterVariables { get; set; }
        public virtual DbSet<SolarLogDevice> SolarLogDevices { get; set; }
        public virtual DbSet<SolarLogVariable> SolarLogVariables { get; set; }
        public virtual DbSet<UbidotsDevice> UbidotsDevices { get; set; }
        public virtual DbSet<UbidotsVariable> UbidotsVariables { get; set; }
        public virtual DbSet<VoltageControllerDevice> VoltageControllerDevices { get; set; }
    }
}
