//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FroniusDataManagerVariable
    {
        public short ID { get; set; }
        public short DeviceID { get; set; }
        public string Name { get; set; }
        public int VectorPosition { get; set; }
        public string Unit { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
