//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartMeterDevice
    {
        public short ID { get; set; }
        public short DeviceID { get; set; }
        public short Port { get; set; }
        public string Password { get; set; }
        public double HighVoltage { get; set; }
        public double LowVoltage { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
